### PR TITLE
Minor `main.rs` refactoring

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by mvines** [comment]
@t-nelson - can I get a quick sanity check on a2e119e3140aca9e4de3c0c069d13b76648e05b5 please.   This commit aligns the `infrastructure_concentration_warnings` notifications with the rest (prelude to a larger refactor of how the notifications are managed)

**Comment by mvines** [comment]
🤔 Github Actions are MIA.  Now what...

**Comment by mvines** [comment]
Ah!  Thar we go.  Good to know that Github Actions share the same webhook race as [ci-gate](https://github.com/mvines/ci-gate)

**Comment by t-nelson** [comment]
> @t-nelson - can I get a quick sanity check on [a2e119e](https://github.com/solana-labs/stake-o-matic/commit/a2e119e3140aca9e4de3c0c069d13b76648e05b5) please. This commit aligns the `infrastructure_concentration_warnings` notifications with the rest (prelude to a larger refactor of how the notifications are managed)

Looks good!

**Pull request merged**
